setImmersiveMode(true)

usePreviousSnap(false)

FolderExists(scriptPath().. "image")
--------------CAMP
FolderExists(scriptPath().. "image/Camp")
	ChecknDownload("Camp/CampBtn.png")
	ChecknDownload("Camp/CampBtnClicked.png")
FolderExists(scriptPath().. "image/Camp/AdventureGuild")
	ChecknDownload("Camp/AdventureGuild/Authority.png")
	ChecknDownload("Camp/AdventureGuild/CampAdventureGuild.png")
	ChecknDownload("Camp/AdventureGuild/CampAdventureGuildClicked.png")
	ChecknDownload("Camp/AdventureGuild/CampAdventureGuildDailyQuest.png")
	ChecknDownload("Camp/AdventureGuild/CampAdventureGuildDailyQuestClaim.png")
	ChecknDownload("Camp/AdventureGuild/CampAdventureGuildDailyQuestClicked.png")
	ChecknDownload("Camp/AdventureGuild/DailyQuest.png")
	ChecknDownload("Camp/AdventureGuild/GoldenFinger.png")
	ChecknDownload("Camp/AdventureGuild/GoldenFingerClick.png")
	ChecknDownload("Camp/AdventureGuild/GoldenFingerClicked.png")
	ChecknDownload("Camp/AdventureGuild/MakeAWish.png")
	ChecknDownload("Camp/AdventureGuild/NoWish.png")
	ChecknDownload("Camp/AdventureGuild/RewardObtained.png")
	ChecknDownload("Camp/AdventureGuild/Skip.png")
	ChecknDownload("Camp/AdventureGuild/StatusClaim.png")
	ChecknDownload("Camp/AdventureGuild/StatusClaimed.png")
	ChecknDownload("Camp/AdventureGuild/StatusPending.png")
	ChecknDownload("Camp/AdventureGuild/WeeklyQuest.png")
	ChecknDownload("Camp/AdventureGuild/Wish.png")
	ChecknDownload("Camp/AdventureGuild/WishCoin.png")
	ChecknDownload("Camp/AdventureGuild/WishCoinClick.png")
	ChecknDownload("Camp/AdventureGuild/WishCoinClicked.png")
FolderExists(scriptPath().. "image/Camp/Arena")
	ChecknDownload("Camp/Arena/5Victories.png")
	ChecknDownload("Camp/Arena/ArenaBtn.png")
	ChecknDownload("Camp/Arena/ArenaLogo.png")
	ChecknDownload("Camp/Arena/ChallengeBtn.png")
	ChecknDownload("Camp/Arena/DefeatExit.png")
	ChecknDownload("Camp/Arena/OpponentTeam.png")
	ChecknDownload("Camp/Arena/ScrollFrom.png")
	ChecknDownload("Camp/Arena/ScrollTo.png")
	ChecknDownload("Camp/Arena/StartChallenge.png")
	ChecknDownload("Camp/Arena/Team2.png")
	ChecknDownload("Camp/Arena/Team3.png")
	ChecknDownload("Camp/Arena/VictoryClaim.png")
	ChecknDownload("Camp/Arena/ZeroAttempts.png")
FolderExists(scriptPath().. "image/Camp/HeroTraining")
	ChecknDownload("Camp/HeroTraining/BasicTrainingGround.png")
	ChecknDownload("Camp/HeroTraining/BasicTrainingGroundStartChallenge.png")
	ChecknDownload("Camp/HeroTraining/HeroTrainingGround.png")
	ChecknDownload("Camp/HeroTraining/HeroTrainingGround2.png")
	ChecknDownload("Camp/HeroTraining/HeroTrainingGroundBasicBackBtn.png")
	ChecknDownload("Camp/HeroTraining/HeroTrainingGroundBasicPoints.png")
	ChecknDownload("Camp/HeroTraining/Points.png")
	ChecknDownload("Camp/HeroTraining/SpeedX.png")

--------------Character
FolderExists(scriptPath().. "image/Character")
	ChecknDownload("Character/CharBtn.png")
	ChecknDownload("Character/CharBtnClicked.png")
FolderExists(scriptPath().. "image/Character/Bag")
	ChecknDownload("Character/Bag/BagBtn.png")
	ChecknDownload("Character/Bag/Cancel.png")
	ChecknDownload("Character/Bag/EquipmentScreen.png")
	ChecknDownload("Character/Bag/Smelt.png")
FolderExists(scriptPath().. "image/Character/Equip")
	ChecknDownload("Character/Equip/CharGearEnhancement.png")
	ChecknDownload("Character/Equip/CharGearEnhancementQuickFuse.png")
	ChecknDownload("Character/Equip/CharGearEnhancementQuickFuse0.png")
	ChecknDownload("Character/Equip/CharGearEnhancementQuickFuseCloseBtn.png")
	ChecknDownload("Character/Equip/CharGearEnhancementQuickGem.png")
	ChecknDownload("Character/Equip/CharGearEnhancementQuickGemClicked.png")
	ChecknDownload("Character/Equip/CharQuickEnhance.png")
	ChecknDownload("Character/Equip/CharQuickEquip.png")
	ChecknDownload("Character/Equip/QuickFuse0.png")
FolderExists(scriptPath().. "image/Character/Skill")
	ChecknDownload("Character/Skill/Hunting.png")
	ChecknDownload("Character/Skill/QuickBreakthroughGray.png")
	ChecknDownload("Character/Skill/QuickBreakthroughYellow.png")
	ChecknDownload("Character/Skill/SelectToContinue.png")
	ChecknDownload("Character/Skill/Skill1.png")
	ChecknDownload("Character/Skill/Skill2.png")
	ChecknDownload("Character/Skill/Skill3.png")
	ChecknDownload("Character/Skill/Skill4.png")
	ChecknDownload("Character/Skill/Skill5.png")
	ChecknDownload("Character/Skill/Skill6.png")
	ChecknDownload("Character/Skill/SkillBtn.png")
	ChecknDownload("Character/Skill/SkillBtnClicked.png")
	ChecknDownload("Character/Skill/SkillsStorageClicked.png")
	ChecknDownload("Character/Skill/SkillStorage.png")
--------------Fight
FolderExists(scriptPath().. "image/Fight")
	ChecknDownload("Fight/Fight.png")
	ChecknDownload("Fight/FightClicked.png")
FolderExists(scriptPath().. "image/Fight/AutoAttack")
	ChecknDownload("Fight/AutoAttack/Challenge.png")
	ChecknDownload("Fight/AutoAttack/ChallengeLogo.png")
	ChecknDownload("Fight/AutoAttack/Fighting.png")
	ChecknDownload("Fight/AutoAttack/Hunting.png")
FolderExists(scriptPath().. "image/Fight/HareBurrow")
	ChecknDownload("Fight/HareBurrow/HareBurrowBtn.png")
FolderExists("Fight/HareBurrow/Exploration")
--ChecknDownload("Fight/HareBurrow/Exploration/SkillStorage.png")
FolderExists(scriptPath().. "image/Fight/HareBurrow/GiftBunny")
	ChecknDownload("Fight/HareBurrow/GiftBunny/AllMaps.png")
	ChecknDownload("Fight/HareBurrow/GiftBunny/Answer1.png")
	ChecknDownload("Fight/HareBurrow/GiftBunny/Answer2.png")
	ChecknDownload("Fight/HareBurrow/GiftBunny/Answer3.png")
	ChecknDownload("Fight/HareBurrow/GiftBunny/GiftBunnyBtn.png")
	ChecknDownload("Fight/HareBurrow/GiftBunny/HareBurrow.png")
	ChecknDownload("Fight/HareBurrow/GiftBunny/Question1.png")
FolderExists(scriptPath().. "image/Fight/QuickBattle")
	ChecknDownload("Fight/QuickBattle/FreePrayer.png")
	ChecknDownload("Fight/QuickBattle/QuickBattle.png")
	ChecknDownload("Fight/QuickBattle/Rhea.png")
	ChecknDownload("Fight/QuickBattle/RheaConfirm.png")
	ChecknDownload("Fight/QuickBattle/RheaStatue.png")
	ChecknDownload("Fight/QuickBattle/RheaX.png")
	ChecknDownload("Fight/QuickBattle/TickAcceleration.png")
	ChecknDownload("Fight/QuickBattle/TickBackupClearance.png")
--------------Market
FolderExists(scriptPath().. "image/Market")
	ChecknDownload("Market/Market.png")
	ChecknDownload("Market/MarketClicked.png")
FolderExists(scriptPath().. "image/Market/Cook")
	ChecknDownload("Market/Cook/Cook.png")
	ChecknDownload("Market/Cook/CookingCook.png")
	ChecknDownload("Market/Cook/CookingCooking.png")
	ChecknDownload("Market/Cook/CookSkip.png")
	ChecknDownload("Market/Cook/CookStorage.png")
	ChecknDownload("Market/Cook/Recipes.png")
	ChecknDownload("Market/Cook/ViewRecipe.png")
	ChecknDownload("Market/Cook/ViewRecipeBack.png")
FolderExists(scriptPath().. "image/Market/Cook/FoodList")
	ChecknDownload("Market/Cook/FoodList/Food1.png")
	ChecknDownload("Market/Cook/FoodList/Food2.png")
	ChecknDownload("Market/Cook/FoodList/Food3.png")
	ChecknDownload("Market/Cook/FoodList/Food4.png")
	ChecknDownload("Market/Cook/FoodList/Food5.png")
	ChecknDownload("Market/Cook/FoodList/Food6.png")
	ChecknDownload("Market/Cook/FoodList/Food7.png")
	ChecknDownload("Market/Cook/FoodList/Food8.png")
	ChecknDownload("Market/Cook/FoodList/Food9.png")
	ChecknDownload("Market/Cook/FoodList/Food10.png")
	ChecknDownload("Market/Cook/FoodList/Food11.png")
	ChecknDownload("Market/Cook/FoodList/Food12.png")
	ChecknDownload("Market/Cook/FoodList/Food13.png")
	ChecknDownload("Market/Cook/FoodList/Food14.png")
	ChecknDownload("Market/Cook/FoodList/Food15.png")
	ChecknDownload("Market/Cook/FoodList/Food16.png")
	ChecknDownload("Market/Cook/FoodList/Food17.png")
	ChecknDownload("Market/Cook/FoodList/Food18.png")
	ChecknDownload("Market/Cook/FoodList/Food19.png")
	ChecknDownload("Market/Cook/FoodList/Food20.png")
	ChecknDownload("Market/Cook/FoodList/Food21.png")
	ChecknDownload("Market/Cook/FoodList/Food22.png")
	ChecknDownload("Market/Cook/FoodList/Food23.png")
	ChecknDownload("Market/Cook/FoodList/Food24.png")
	ChecknDownload("Market/Cook/FoodList/Food25.png")
--------------OCR
FolderExists(scriptPath().. "image/OCR")
	ChecknDownload("OCR/CP.png")
	ChecknDownload("OCR/cp0.png")
	ChecknDownload("OCR/cp1.png")
	ChecknDownload("OCR/cp2.png")
	ChecknDownload("OCR/cp3.png")
	ChecknDownload("OCR/cp4.png")
	ChecknDownload("OCR/cp5.png")
	ChecknDownload("OCR/cp6.png")
	ChecknDownload("OCR/cp7.png")
	ChecknDownload("OCR/cp8.png")
	ChecknDownload("OCR/cp9.png")
	ChecknDownload("OCR/Team1.png")
	ChecknDownload("OCR/Team2.png")
	ChecknDownload("OCR/Team3.png")
--------------Pet
FolderExists(scriptPath().. "image/Pet")
	ChecknDownload("Pet/Acquired.png")
	ChecknDownload("Pet/PetBtn.png")
	ChecknDownload("Pet/PetBtnClicked.png")
	ChecknDownload("Pet/PetPetBtn.png")
	ChecknDownload("Pet/PetPetBtnClicked.png")
	ChecknDownload("Pet/ReadAll.png")
FolderExists(scriptPath().. "image/Pet/LuckyRuins")
	ChecknDownload("Pet/LuckyRuins/PetLuckyRuinsBackBtn.png")
	ChecknDownload("Pet/LuckyRuins/PetLuckyRuinsBtn.png")
	ChecknDownload("Pet/LuckyRuins/PetLuckyRuinsClicked.png")
	ChecknDownload("Pet/LuckyRuins/PetLuckyRuinsFreeBtn.png")
	ChecknDownload("Pet/LuckyRuins/PetLuckyRuinsFreeBtn2.png")
	ChecknDownload("Pet/LuckyRuins/PetLuckyRuinsFreeClicked.png")
FolderExists(scriptPath().. "image/Pet/PetAdventure")
	ChecknDownload("Pet/PetAdventure/PetAdventureBtn.png")
	ChecknDownload("Pet/PetAdventure/PetAdventureBtnClicked.png")
	ChecknDownload("Pet/PetAdventure/PetAdventureClaimAllBtn.png")
	ChecknDownload("Pet/PetAdventure/PetAdventureFinished.png")
	ChecknDownload("Pet/PetAdventure/PetAdventureQuickAdventureBtn.png")
	ChecknDownload("Pet/PetAdventure/PetAdventureQuickJoinBtn.png")
	ChecknDownload("Pet/PetAdventure/PetAdventureStartAdventureBtn.png")
	ChecknDownload("Pet/PetAdventure/PetAdventureStartAdventureConfirmBtn.png")
	ChecknDownload("Pet/PetAdventure/PetAdventureTaptoContinue.png")
FolderExists(scriptPath().. "image/Pet/PetCapture")
	ChecknDownload("Pet/PetCapture/Cook.png")
	ChecknDownload("Pet/PetCapture/PetCaptureBtn.png")
	ChecknDownload("Pet/PetCapture/PetCaptureBtnClicked.png")
	ChecknDownload("Pet/PetCapture/PetCaptureCaptureBtn.png")
	ChecknDownload("Pet/PetCapture/PetCaptureGiveUpBtn.png")
	ChecknDownload("Pet/PetCapture/PetCapturePetBtn.png")
	ChecknDownload("Pet/PetCapture/PetCaptureSkip.png")
	ChecknDownload("Pet/PetCapture/PetSelectFoodConfirmBtn.png")
	ChecknDownload("Pet/PetCapture/PetTaptoContinue.png")
	ChecknDownload("Pet/PetCapture/SelectFood.png")
FolderExists(scriptPath().. "image/Pet/PetRelease")
	ChecknDownload("Pet/PetRelease/PetReleaseBtn.png")
	ChecknDownload("Pet/PetRelease/PetReleaseByQuality.png")
	ChecknDownload("Pet/PetRelease/PetReleaseConfirmBtn.png")
	ChecknDownload("Pet/PetRelease/PetReleaseList.png")
	ChecknDownload("Pet/PetRelease/PetReleaseQualityEpic.png")
	ChecknDownload("Pet/PetRelease/PetReleaseQualityEpicClicked.png")
	ChecknDownload("Pet/PetRelease/PetReleaseQualityNormal.png")
	ChecknDownload("Pet/PetRelease/PetReleaseQualityNormalClicked.png")
	ChecknDownload("Pet/PetRelease/PetReleaseQualityRare.png")
	ChecknDownload("Pet/PetRelease/PetReleaseQualityRareClicked.png")
	ChecknDownload("Pet/PetRelease/PetReleaseQualityUncommon.png")
	ChecknDownload("Pet/PetRelease/PetReleaseQualityUncommonClicked.png")
	ChecknDownload("Pet/PetRelease/PetReleaseTaptoContinue.png")
	ChecknDownload("Pet/PetRelease/PetSelected.png")
	ChecknDownload("Pet/PetRelease/PetSelection.png")